import { readFile } from 'node:fs/promises';

import ky from 'ky';
import { describe, expect, test } from 'vitest';

import { Novelup } from '@/web/novelup';
import { WebNovelType } from '@/web/types';
import { client } from './utils';

async function createFixtureProvider(filename: string): Promise<Novelup> {
  const html = await readFile(
    new URL(`../fixtures/novelup/${filename}`, import.meta.url),
    'utf8',
  );

  return new Novelup(
    ky.create({
      fetch: async (input) => {
        const url =
          typeof input === 'string'
            ? input
            : input instanceof URL
              ? input.href
              : input.url;
        const body = new URL(url).searchParams.has('p')
          ? '<div class="episodeList"></div>'
          : html;
        return new Response(body, {
          status: 200,
          headers: { 'Content-Type': 'text/html; charset=utf-8' },
        });
      },
    }),
  );
}

describe('novelup parser', () => {
  test('parses 914883178', async () => {
    const provider = await createFixtureProvider('914883178.260816.html');

    const metadata = await provider.getMetadata('914883178');

    expect(metadata.title).toBe('読んでみませんか？');
    expect(metadata.authors).toEqual([
      {
        name: '野上',
        link: 'https://novelup.plus/user/389076608/profile',
      },
    ]);
    expect(metadata.type).toBe(WebNovelType.Ongoing);
    expect(metadata.keywords).toEqual([
      'ノベプラオンリー',
      '顔文字ーズ',
      'ありがとうノベプラ',
      '読書ログ',
      '無理せず気楽に楽しく',
      '第5回HJ大賞',
    ]);
    expect(metadata.points).toBe(6_116_146);
    expect(metadata.totalCharacters).toBe(2_718_848);
    expect(metadata.introduction).toContain('顔文字ーずによる読書ログ');
  });

  test('parses a chapter response', async () => {
    const provider = new Novelup(
      ky.create({
        fetch: async () =>
          new Response('<p id="episode_content">第一段\n第二段</p>', {
            status: 200,
            headers: { 'Content-Type': 'text/html; charset=utf-8' },
          }),
      }),
    );

    const chapter = await provider.getChapter('521606819', '786941040');

    expect(chapter.paragraphs).toEqual(['第一段', '第二段']);
  });

  test('identifies a CloudFront block before parsing HTML', async () => {
    const provider = new Novelup(
      ky.create({
        fetch: async () =>
          new Response(
            '<h1>403 ERROR</h1><p>Request blocked.</p><p>Generated by cloudfront</p>',
            { status: 403, statusText: 'Forbidden' },
          ),
      }),
    );

    await expect(provider.getMetadata('521606819')).rejects.toThrow(
      '触发 CloudFront 人机验证',
    );
  });
});

describe('novelup', () => {
  const provider = new Novelup(client);

  test('metadata', async () => {
    // 俺が魔法少女になるんだよ！
    // https://novelup.plus/story/634490929
    const novelId = '634490929';

    const data = await provider.getMetadata(novelId);
    expect(data).toBeDefined();
    expect(data?.title).toBe('俺が魔法少女になるんだよ！');
    expect(data?.type).toBeDefined();
    expect(data?.attentions).toEqual([]);
    expect(data?.keywords.join('\n')).contain('TS');
    expect(data?.keywords.join('\n')).contain('魔法少女');
    expect(data?.introduction).toBeDefined();
    expect(data?.toc?.[1]?.title).contain('Are You "Lady"');
  });

  test('chapter', async () => {
    // 俺が魔法少女になるんだよ！
    // https://novelup.plus/story/634490929
    const novelId = '634490929';
    const chapterId = '248478336';

    const data = await provider.getChapter(novelId, chapterId);
    expect(data).toBeDefined();
    const text = data.paragraphs.join('\n');
    expect(text).contain('魔法少女がいるのだから');
  });
});
